GET http://localhost:3003/api/users

###
DELETE http://localhost:3003/api/users/1


###
POST http://localhost:3003/api/users HTTP/1.1
content-Type: application/json

{
    "username": "hellas",
    "name": "Arto Hellas",
    "password": "hellas"
}